---
- name: Deploy Django app on the ubuntu server
  hosts: pythondemo
  remote_user: ubuntu
  tasks:
    - name: remove existing project folder
      shell: rm -rf project
      args:
        chdir: /home/ubuntu/project/
    - name: pull the code from s3 bucket
      shell: aws s3 cp s3://ayes-demo-builds/project-{{version}}.tar.gz project.tar.gz
      args: 
        creates: project.tar.gz
        chdir: /home/ubuntu/project/
    - name: unzip the tar file
      shell: tar -xvf project.tar.gz
      args:              
        chdir: /home/ubuntu/project/
    - name: restarting gunicorn
      become: true
      become_method: sudo
      become_user: root
      command: systemctl restart  project.service 
    - name: status of  gunicorn
      become: true
      become_method: sudo
      become_user: root
      command: systemctl status project.service
    - name: remove the tar files
      shell: rm /home/ubuntu/project/project.tar.gz